name: devhub
description: A comprehensive college project app for beginner programmers to foster genuine coding skills.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.2
  url_launcher: ^6.2.2
  url_launcher_web: ^2.2.0
  intl: ^0.18.1
  flutter_highlight: ^0.7.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
